# use with build-arm64.sh
FROM gcr.io/distroless/cc

#! replace this with the name of the rust project
ARG APP_NAME="hello_rust"

COPY ./target/aarch64-unknown-linux-gnu/release/${APP_NAME} /app

CMD ["/app"]
