# builds and runs using a lighter node alpine image
# great for smaller image size
FROM node:lts-alpine

WORKDIR /app

COPY package*.json .
COPY yarn.lock .

RUN yarn install

COPY . .

EXPOSE 8080

CMD ["yarn", "start"]
